services:
  api_gateway:
    build:
      context: ./src
      dockerfile: ./api_gateway/Dockerfile
      args:
        - API_PORT
    container_name: api_gateway
    working_dir: /usr/src/app
    depends_on:
        user:
          condition: service_healthy
    healthcheck:
      test: "curl http://api_gateway:8080/health"
      interval: 15s
      timeout: 1s
      retries: 5

    ports:
      - "8080:8080"
    env_file:
      - ".db_env"
      - ".user_env"

  db_node_1:
    build: ./src/database/postgres
    container_name: postgres_db
    ports:
      - "5432:5432"
    env_file:
      - ".db_env"
    healthcheck:
      test: "psql -h localhost -U postgres -d company"
      interval: 15s
      timeout: 1s
      retries: 5
    volumes:
      - postgres_data:/var/lib/postgresql/data

  user:
    build: 
      context: ./src
      dockerfile: ./services/user/Dockerfile
      args:
        - USER_SERVICE_PORT
    container_name: user
    working_dir: /usr/src/app
    ports:
      - "50051:50051"
    env_file:
      - ".user_env"
    depends_on:
        db_node_1:
          condition: service_healthy

    healthcheck:
      test: "./grpc-health-probe -addr=user:50051"
      interval: 15s
      timeout: 1s
      retries: 5

volumes:
  postgres_data: